version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: ${LOCAL_CH_DB}
      CLICKHOUSE_USER: ${LOCAL_CH_USER}
      CLICKHOUSE_PASSWORD: ${LOCAL_CH_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      TZ: Asia/Seoul
    ports:
      - "8123:8123"   # HTTP 인터페이스
      - "9000:9000"   # Native 인터페이스
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - app_network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 131072
        hard: 131072
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined
volumes:
  clickhouse_data:
    driver: local

networks:
  app_network:
    name: app_network
    driver: bridge