version: '3.8'
services:

  redis:
    image: redis:latest
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - server-blue
      - server-green
    networks:
      - app-network

  server-blue:
    image: ghcr.io/boostcampwm-2024/web35-watchducks/backend/console-server:latest
    container_name: app-server-blue-1
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
      - PORT=3001
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 10s
      timeout: 2s
      retries: 5
    networks:
      - app-network

  server-green:
    image: ghcr.io/boostcampwm-2024/web35-watchducks/backend/console-server:latest
    container_name: app-server-green-1
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
      - PORT=3002
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3002"]
      interval: 10s
      timeout: 2s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge