version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server-blue
      - server-green

  server-blue:
    image: ghcr.io/boostcampwm-2024/web35-watchducks/backend/console-server:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env

  server-green:
    image: ghcr.io/boostcampwm-2024/web35-watchducks/backend/console-server:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env