version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "5353:5353/udp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server-blue
      - server-green
    networks:
      - app-network

  server-blue:
    image: ghcr.io/boostcampwm-2024/web35-watchducks/backend/name-server:latest
    environment:
      - NODE_ENV=production
      - NAME_SERVER_PORT=3001
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 10s
      timeout: 2s
      retries: 5
    networks:
      - app-network

  server-green:
    image: ghcr.io/boostcampwm-2024/web35-watchducks/backend/name-server:latest
    environment:
      - NODE_ENV=production
      - NAME_SERVER_PORT=3002
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3002"]
      interval: 10s
      timeout: 2s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge